// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_file_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_file_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_file_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_file_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_file_2eproto;
class CarrotFile;
struct CarrotFileDefaultTypeInternal;
extern CarrotFileDefaultTypeInternal _CarrotFile_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CarrotFile* Arena::CreateMaybeMessage<::CarrotFile>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class CarrotFile final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CarrotFile) */ {
 public:
  inline CarrotFile() : CarrotFile(nullptr) {}
  ~CarrotFile() override;
  explicit PROTOBUF_CONSTEXPR CarrotFile(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CarrotFile(const CarrotFile& from);
  CarrotFile(CarrotFile&& from) noexcept
    : CarrotFile() {
    *this = ::std::move(from);
  }

  inline CarrotFile& operator=(const CarrotFile& from) {
    CopyFrom(from);
    return *this;
  }
  inline CarrotFile& operator=(CarrotFile&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CarrotFile& default_instance() {
    return *internal_default_instance();
  }
  static inline const CarrotFile* internal_default_instance() {
    return reinterpret_cast<const CarrotFile*>(
               &_CarrotFile_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CarrotFile& a, CarrotFile& b) {
    a.Swap(&b);
  }
  inline void Swap(CarrotFile* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CarrotFile* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CarrotFile* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CarrotFile>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CarrotFile& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CarrotFile& from) {
    CarrotFile::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CarrotFile* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CarrotFile";
  }
  protected:
  explicit CarrotFile(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPathnameFieldNumber = 2,
    kSyscallNumFieldNumber = 1,
    kFlagsFieldNumber = 3,
    kModeFieldNumber = 4,
  };
  // string pathname = 2;
  void clear_pathname();
  const std::string& pathname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pathname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pathname();
  PROTOBUF_NODISCARD std::string* release_pathname();
  void set_allocated_pathname(std::string* pathname);
  private:
  const std::string& _internal_pathname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pathname(const std::string& value);
  std::string* _internal_mutable_pathname();
  public:

  // int32 syscall_num = 1;
  void clear_syscall_num();
  int32_t syscall_num() const;
  void set_syscall_num(int32_t value);
  private:
  int32_t _internal_syscall_num() const;
  void _internal_set_syscall_num(int32_t value);
  public:

  // int32 flags = 3;
  void clear_flags();
  int32_t flags() const;
  void set_flags(int32_t value);
  private:
  int32_t _internal_flags() const;
  void _internal_set_flags(int32_t value);
  public:

  // int32 mode = 4;
  void clear_mode();
  int32_t mode() const;
  void set_mode(int32_t value);
  private:
  int32_t _internal_mode() const;
  void _internal_set_mode(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:CarrotFile)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pathname_;
    int32_t syscall_num_;
    int32_t flags_;
    int32_t mode_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_file_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CarrotFile

// int32 syscall_num = 1;
inline void CarrotFile::clear_syscall_num() {
  _impl_.syscall_num_ = 0;
}
inline int32_t CarrotFile::_internal_syscall_num() const {
  return _impl_.syscall_num_;
}
inline int32_t CarrotFile::syscall_num() const {
  // @@protoc_insertion_point(field_get:CarrotFile.syscall_num)
  return _internal_syscall_num();
}
inline void CarrotFile::_internal_set_syscall_num(int32_t value) {
  
  _impl_.syscall_num_ = value;
}
inline void CarrotFile::set_syscall_num(int32_t value) {
  _internal_set_syscall_num(value);
  // @@protoc_insertion_point(field_set:CarrotFile.syscall_num)
}

// string pathname = 2;
inline void CarrotFile::clear_pathname() {
  _impl_.pathname_.ClearToEmpty();
}
inline const std::string& CarrotFile::pathname() const {
  // @@protoc_insertion_point(field_get:CarrotFile.pathname)
  return _internal_pathname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CarrotFile::set_pathname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.pathname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:CarrotFile.pathname)
}
inline std::string* CarrotFile::mutable_pathname() {
  std::string* _s = _internal_mutable_pathname();
  // @@protoc_insertion_point(field_mutable:CarrotFile.pathname)
  return _s;
}
inline const std::string& CarrotFile::_internal_pathname() const {
  return _impl_.pathname_.Get();
}
inline void CarrotFile::_internal_set_pathname(const std::string& value) {
  
  _impl_.pathname_.Set(value, GetArenaForAllocation());
}
inline std::string* CarrotFile::_internal_mutable_pathname() {
  
  return _impl_.pathname_.Mutable(GetArenaForAllocation());
}
inline std::string* CarrotFile::release_pathname() {
  // @@protoc_insertion_point(field_release:CarrotFile.pathname)
  return _impl_.pathname_.Release();
}
inline void CarrotFile::set_allocated_pathname(std::string* pathname) {
  if (pathname != nullptr) {
    
  } else {
    
  }
  _impl_.pathname_.SetAllocated(pathname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.pathname_.IsDefault()) {
    _impl_.pathname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:CarrotFile.pathname)
}

// int32 flags = 3;
inline void CarrotFile::clear_flags() {
  _impl_.flags_ = 0;
}
inline int32_t CarrotFile::_internal_flags() const {
  return _impl_.flags_;
}
inline int32_t CarrotFile::flags() const {
  // @@protoc_insertion_point(field_get:CarrotFile.flags)
  return _internal_flags();
}
inline void CarrotFile::_internal_set_flags(int32_t value) {
  
  _impl_.flags_ = value;
}
inline void CarrotFile::set_flags(int32_t value) {
  _internal_set_flags(value);
  // @@protoc_insertion_point(field_set:CarrotFile.flags)
}

// int32 mode = 4;
inline void CarrotFile::clear_mode() {
  _impl_.mode_ = 0;
}
inline int32_t CarrotFile::_internal_mode() const {
  return _impl_.mode_;
}
inline int32_t CarrotFile::mode() const {
  // @@protoc_insertion_point(field_get:CarrotFile.mode)
  return _internal_mode();
}
inline void CarrotFile::_internal_set_mode(int32_t value) {
  
  _impl_.mode_ = value;
}
inline void CarrotFile::set_mode(int32_t value) {
  _internal_set_mode(value);
  // @@protoc_insertion_point(field_set:CarrotFile.mode)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_file_2eproto
